stages:
    - build
    - test

build:
    stage: build
    script:
        - echo "Build"
        - docker build --tag islasgeci .
        - docker run islasgeci make tests
        - docker run islasgeci make mutants
        - mkdir build
        - touch build/info.txt
    artifacts:
        paths:
            - build/

test:
    stage: test
    script:
        - echo "Testing"
        - test -f "build/info.txt"